/**************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are subject to the Mozilla Public License, v. 2.0.
 If a copy of the MPL was not distributed with this file, You can obtain one
 at http://mozilla.org/MPL/2.0/.

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 for the specific language governing rights and limitations under the License.

 Copyright (C) 2019 Botts Innovative Research, Inc. All Rights Reserved.
 ******************************* END LICENSE BLOCK ***************************/

package org.sensorhub.impl.driver.spotreport;

import net.opengis.swe.v20.DataBlock;
import net.opengis.swe.v20.DataComponent;
import net.opengis.swe.v20.DataEncoding;
import net.opengis.swe.v20.Quantity;
import net.opengis.swe.v20.Text;
import net.opengis.swe.v20.Time;
import net.opengis.swe.v20.Vector;

import org.sensorhub.api.sensor.SensorDataEvent;
import org.sensorhub.api.sensor.SensorException;
import org.sensorhub.impl.sensor.AbstractSensorOutput;
//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;
import org.vast.data.AbstractDataBlock;
import org.vast.data.DataBlockMixed;
import org.vast.swe.SWEHelper;
import org.vast.swe.helper.GeoPosHelper;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.ResultReceiver;
import android.util.Log;

import java.util.UUID;

/**
 * <p>
 * Implementation of data interface for Spot Reports
 * </p>
 *
 * @author Nicolas Garay <nicolasgaray@icloud.com>
 * @since Nov 9, 2019
 */
public class SpotReportAidOutput extends AbstractSensorOutput<SpotReportDriver> {

    // keep logger name short because in LogCat it's max 23 chars
//    private static final Logger log = LoggerFactory.getLogger(SpotReportOutput.class.getSimpleName());

    // Data Associated with Broadcast Receivers and Intents
    private static final String ACTION_SUBMIT_AID_REPORT = "org.sensorhub.android.intent.SPOT_REPORT_AID";
    private static final int SUBMIT_REPORT_FAILURE = 0;
    private static final int SUBMIT_REPORT_SUCCESS = 1;

    private static final String DATA_LAT = "lat";
    private static final String DATA_LON = "lon";
    private static final String DATA_RADIUS = "radius";
    private static final String DATA_AID_TYPE = "aidType";
    private static final String DATA_NUM_PERSONS = "numPersons";
    private static final String DATA_URGENCY = "urgency";
    private static final String DATA_DESCRIPTION = "description";
    private static final String DATA_REPORTER = "reporter";
    private SpotReportReceiver broadcastReceiver = new SpotReportReceiver();

    // SWE DataBlock elements
    private static final String DATA_RECORD_REPORT_TIME_LABEL = "time";
    private static final String DATA_RECORD_REPORT_ID_LABEL = "id";
    private static final String DATA_RECORD_REPORT_LOC_LABEL = "location";
    private static final String DATA_RECORD_REPORT_RADIUS_LABEL = "radius";
    private static final String DATA_RECORD_REPORT_AID_TYPE_LABEL = "aidType";
    private static final String DATA_RECORD_REPORT_NUM_PERSONS_LABEL = "numPersons";
    private static final String DATA_RECORD_REPORT_URGENCY_LABEL = "urgency";
    private static final String DATA_RECORD_REPORT_DESCRIPTION_LABEL = "description";
    private static final String DATA_RECORD_REPORT_REPORTER_LABEL = "reporter";

    private static final String DATA_RECORD_NAME = "Aid Spot Report";
    private static final String DATA_RECORD_DESCRIPTION =
            "A report generated by visual observance and classification which is accompanied by a" +
                    " location, description, and other data";
    private static final String DATA_RECORD_DEFINITION =
            SWEHelper.getPropertyUri("AidSpotReport");

    private DataComponent dataStruct;
    private DataEncoding dataEncoding;

    private Context context;
    private String name;

    SpotReportAidOutput(SpotReportDriver parentModule) {

        super(parentModule);
        this.name = "aid_spot_report_data";
        context = getParentModule().getConfiguration().androidContext;
    }

    @Override
    public String getName() {

        return name;
    }

    /**
     * Initialize the output data structure
     *
     * @throws SensorException
     */
    void init() throws SensorException {

        // Build data structure ********************************************************************
        SWEHelper sweHelper = new SWEHelper();
        dataStruct = sweHelper.newDataRecord();
        dataStruct.setDescription(DATA_RECORD_DESCRIPTION);
        dataStruct.setDefinition(DATA_RECORD_DEFINITION);
        dataStruct.setName(DATA_RECORD_NAME);

        // Add time stamp component to data record
        Time time = sweHelper.newTimeStampIsoUTC();
        dataStruct.addComponent(DATA_RECORD_REPORT_TIME_LABEL, time);

        Text id = sweHelper.newText(SWEHelper.getPropertyUri("ID"),
                "ID",
                "A unique identifier for the report");
        dataStruct.addComponent(DATA_RECORD_REPORT_ID_LABEL, id);

        // Add the location component of the data record
        GeoPosHelper geoPosHelper = new GeoPosHelper();
        Vector locationVectorLLA = geoPosHelper.newLocationVectorLLA(null);
        locationVectorLLA.setLocalFrame(parentSensor.localFrameURI);
        dataStruct.addComponent(DATA_RECORD_REPORT_LOC_LABEL, locationVectorLLA);

        Quantity radius = sweHelper.newQuantity(SWEHelper.getPropertyUri("Radius"),
                "Radius",
                "Radius in ft. of reported location where observation may be contained or found",
                "ft.");
        dataStruct.addComponent(DATA_RECORD_REPORT_RADIUS_LABEL, radius);

        Text aidType = sweHelper.newText(SWEHelper.getPropertyUri("AidType"),
                "Aid Type",
                "An identifier of the type of aid required");
        dataStruct.addComponent(DATA_RECORD_REPORT_AID_TYPE_LABEL, aidType);

        Text numPersons = sweHelper.newText(SWEHelper.getPropertyUri("NumPersons"),
                "Number of Persons",
                "A magnitude value denoting the number of persons needing assistance at the location");
        dataStruct.addComponent(DATA_RECORD_REPORT_NUM_PERSONS_LABEL, numPersons);

        Text urgency = sweHelper.newText(SWEHelper.getPropertyUri("Urgency"),
                "Urgency",
                "An identifier of the level of urgency for the need described by this report");
        dataStruct.addComponent(DATA_RECORD_REPORT_URGENCY_LABEL, urgency);

        Text description = sweHelper.newText(SWEHelper.getPropertyUri("Description"),
                "Description",
                "A description of conditions, observation, or other information necessary to convey need of aid");
        dataStruct.addComponent(DATA_RECORD_REPORT_DESCRIPTION_LABEL, description);

        Text reporter = sweHelper.newText(SWEHelper.getPropertyUri("Reporter"),
                "Reporter",
                "An identifier of the person who submitted the report");
        dataStruct.addComponent(DATA_RECORD_REPORT_REPORTER_LABEL, reporter);

        // Setup data encoding *********************************************************************
        this.dataEncoding = sweHelper.newTextEncoding(",", "\n");
    }

    /**
     * Populate and submit an instance of the SpotReport containing no image.
     *
     * @param lat Latitude
     * @param lon Longitude
     * @param radius Radius of validity
     * @param aidType Type of aid being requested
     * @param numPersons Number of persons requiring aid
     * @param urgency Urgency for the aid
     * @param description Description of the observation
     * @param reporter Identifier for person making the report
     */
    private void submitReport(String lat, String lon, int radius, String aidType,
                              String numPersons, String urgency, String description,
                              String reporter) {

        double samplingTime = System.currentTimeMillis() / 1000.0;

        // generate new data record
        DataBlock newRecord;

        if (latestRecord == null) {

            newRecord = dataStruct.createDataBlock();
        } else {

            newRecord = latestRecord.renew();
        }

        newRecord.setDoubleValue(0, samplingTime);
        newRecord.setStringValue(1, UUID.randomUUID().toString());
        newRecord.setDoubleValue(2, Double.parseDouble(lat));
        newRecord.setDoubleValue(3, Double.parseDouble(lon));
        newRecord.setDoubleValue(4, 0.0);
        newRecord.setIntValue(5, radius);
        newRecord.setStringValue(6, aidType);
        newRecord.setStringValue(7, numPersons);
        newRecord.setStringValue(8, urgency);
        newRecord.setStringValue(9, description);
        newRecord.setStringValue(10, reporter);

        // update latest record and send event
        latestRecord = newRecord;
        latestRecordTime = System.currentTimeMillis();
        eventHandler.publishEvent(new SensorDataEvent(latestRecordTime, this, newRecord));
    }

    public void start() {

        context.registerReceiver(broadcastReceiver, new IntentFilter(ACTION_SUBMIT_AID_REPORT));
    }

    @Override
    public void stop() {

        context.unregisterReceiver(broadcastReceiver);
    }

    @Override
    public double getAverageSamplingPeriod() {

        return 1;
    }

    @Override
    public DataComponent getRecordDescription() {

        return dataStruct;
    }

    @Override
    public DataEncoding getRecommendedEncoding() {

        return dataEncoding;
    }

    @Override
    public DataBlock getLatestRecord() {

        return latestRecord;
    }

    @Override
    public long getLatestRecordTime() {

        return latestRecordTime;
    }

    /**
     * Broadcast receiver to register with OS for IPC with SpotReportActivity
     */
    private class SpotReportReceiver extends BroadcastReceiver {

        @Override
        public void onReceive(Context context, Intent intent) {

            ResultReceiver resultReceiver = intent.getParcelableExtra(Intent.EXTRA_RESULT_RECEIVER);

            try {

                if (ACTION_SUBMIT_AID_REPORT.equals(intent.getAction())) {

                    String lat = intent.getStringExtra(DATA_LAT);
                    String lon = intent.getStringExtra(DATA_LON);
                    int radius = intent.getIntExtra(DATA_RADIUS, 0);
                    String aidType = intent.getStringExtra(DATA_AID_TYPE);
                    String numPersons = intent.getStringExtra(DATA_NUM_PERSONS);
                    String urgency = intent.getStringExtra(DATA_URGENCY);
                    String description = intent.getStringExtra(DATA_DESCRIPTION);
                    String reporter = intent.getStringExtra(DATA_REPORTER);

                    submitReport(lat, lon, radius, aidType, numPersons, urgency, description, reporter);

                    resultReceiver.send(SUBMIT_REPORT_SUCCESS, null);

                }

            } catch (Exception e) {

                Log.e("SpotReportOutput", e.toString());
                resultReceiver.send(SUBMIT_REPORT_FAILURE, null);
            }
        }
    }
}
